version: 0.0.{build}

environment:
  personal_access_token:
    secure: YzksXW/AW5tLjUMIWaLl2RoMuR9Ev+8hmISUdD8iQtMDTCyMiLRpqMnlGYNIwzbMdS2vIMmDag7rECZ0qUVZHg== 

cache:
  - node_modules

install:
  - npm install

before_build:
  - npm version %APPVEYOR_BUILD_VERSION%

build_script:
  - npm run build

artifacts:
  - path: '*.vsix'
    name: Installer

test_script:
  - npm run test -- --reporter mocha-appveyor-reporter

deploy:
  provider: GitHub
  release: nuget-reverse-package-search-$(appveyor_build_version).vsix
  auth_token:
    secure: 49tYkCfaLrdmtaZq3BsFNwIv476SZBwHh24WOWZn5C8S9HrlIdfeWWyRx9BFBZXN
  artifact: /.*\.vsix/
  draft: false
  prerelease: false
  on:
    branch: release 

after_deploy:
  - npm run publish -- -p %personal_access_token% 